function g = guessf(u,rb,ri,vu0,A0)

 g = [atan(A0*pi*sin(u*pi)/rb);...
     A0*pi^2*cos(pi*u)/(rb*(1+A0^2*pi^2*sin(pi*u)^2/rb^2));...
     ri+(rb-ri)*u;...
     A0*(1+cos(u*pi));...
     1/2*rb^2*u^2;...
     0;...
     0;...
     0;...
     vu0];
