function [dfdy,dfdp] = jac(u,y,para,fp,ka,mu,Ga1,Ga2,uc,r0c,z0c,psi0c,h0,dt)

psi = y(1);
dpsi = y(2);
r = y(3);
z = y(4);
la = y(6);
al = y(7);
be = y(8);
vu = y(9);
r0 = spline(uc,r0c,u);
z0 = spline(uc,z0c,u);
psi0 = spline(uc,psi0c,u);

c0 = 0;
h = para(1);
fu = 0;
fn = fp;

dfdy=[0,1,0,0,0,0,0,0,0;al.*h.^2.*ka.^(-1).*r.^(-1).*cos(psi)+ h.^2.* ...
  r.^(-2).*cos(psi).^2+ dpsi.*h.*r.^(-1).*sin(psi)+ (-1).*be.*h.^2.* ...
  ka.^(-1).*r.^(-1).*sin(psi)+ (-1).*h.^2.*r.^(-2).*sin(psi).^2,(-1) ...
  .*h.*r.^(-1).*cos(psi),dpsi.*h.*r.^(-2).*cos(psi)+ (-1).*be.*h.^2.* ...
  ka.^(-1).*r.^(-2).*cos(psi)+ (-1).*al.*h.^2.*ka.^(-1).*r.^(-2).* ...
  sin(psi)+ (-2).*h.^2.*r.^(-3).*cos(psi).*sin(psi),0,0,0,h.^2.*ka.^( ...
  -1).*r.^(-1).*sin(psi),h.^2.*ka.^(-1).*r.^(-1).*cos(psi),0;(-1).* ...
  h.*sin(psi),0,0,0,0,0,0,0,0;(-1).*h.*cos(psi),0,0,0,0,0,0,0,0;0,0, ...
  h,0,0,0,0,0,0;(-2).*dpsi.*mu.*r.^(-1).*vu.*cos(psi)+ (-2).* ...
  dpsi.^2.*dt.^(-1).*h.^(-1).*mu.*z.*cos(psi)+ 2.*dpsi.^2.*dt.^(-1).* ...
  h.^(-1).*mu.*(z+ (-1).*z0).*cos(psi)+ 2.*dpsi.^2.*dt.^(-1).*h.^(-1) ...
  .*mu.*z0.*cos(psi)+ 4.*dpsi.*dt.^(-1).*mu.*cos(psi).^2+ 2.*be.*dt.^( ...
  -1).*h.*ka.^(-1).*mu.*cos(psi).^2+ (-2).*be.*dt.^(-1).*h.*ka.^(-1) ...
  .*mu.*r.^(-1).*(r+ (-1).*r0).*cos(psi).^2+ (-2).*dpsi.*dt.^(-1).* ...
  mu.*r.^(-1).*r0.*cos(psi).^2+ (-2).*be.*dt.^(-1).*h.*ka.^(-1).*mu.* ...
  r.^(-1).*r0.*cos(psi).^2+ 2.*al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1) ...
  .*z.*cos(psi).^2+ (-2).*al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*(z+  ...
  (-1).*z0).*cos(psi).^2+ (-2).*al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^( ...
  -1).*z0.*cos(psi).^2+ (-2).*dpsi.*dt.^(-1).*h.^(-1).*h0.*mu.*cos( ...
  psi+ (-1).*psi0)+ (-2).*dpsi.*dt.^(-1).*h.^(-1).*mu.*cos(psi).*(h.* ...
  cos(psi)+ (-1).*h0.*cos(psi0))+ (-2).*dpsi.^2.*dt.^(-1).*h.^(-1).* ...
  mu.*r.*sin(psi)+ 2.*dpsi.^2.*dt.^(-1).*h.^(-1).*mu.*(r+ (-1).*r0).* ...
  sin(psi)+ 2.*dpsi.^2.*dt.^(-1).*h.^(-1).*mu.*r0.*sin(psi)+ 4.*al.* ...
  dt.^(-1).*h.*ka.^(-1).*mu.*cos(psi).*sin(psi)+ (-4).*al.*dt.^(-1).* ...
  h.*ka.^(-1).*mu.*r.^(-1).*(r+ (-1).*r0).*cos(psi).*sin(psi)+ (-4).* ...
  al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*r0.*cos(psi).*sin(psi)+ ( ...
  -4).*dpsi.*dt.^(-1).*mu.*r.^(-1).*z.*cos(psi).*sin(psi)+ (-4).*be.* ...
  dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*z.*cos(psi).*sin(psi)+ 4.*be.* ...
  dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*(z+ (-1).*z0).*cos(psi).*sin( ...
  psi)+ 4.*dpsi.*dt.^(-1).*mu.*r.^(-1).*z0.*cos(psi).*sin(psi)+ 4.* ...
  be.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*z0.*cos(psi).*sin(psi)+ ( ...
  -2).*dt.^(-1).*h0.*mu.*r.^(-1).*cos(psi+ (-1).*psi0).*sin(psi)+ (-2) ...
  .*be.*dt.^(-1).*h.*ka.^(-1).*mu.*sin(psi).^2+ 2.*be.*dt.^(-1).*h.* ...
  ka.^(-1).*mu.*r.^(-1).*(r+ (-1).*r0).*sin(psi).^2+ 2.*dpsi.*dt.^(-1) ...
  .*mu.*r.^(-1).*r0.*sin(psi).^2+ 2.*be.*dt.^(-1).*h.*ka.^(-1).*mu.* ...
  r.^(-1).*r0.*sin(psi).^2+ (-2).*al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^( ...
  -1).*z.*sin(psi).^2+ 2.*al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*(z+  ...
  (-1).*z0).*sin(psi).^2+ 2.*al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).* ...
  z0.*sin(psi).^2+ (-2).*dt.^(-1).*h0.*mu.*r.^(-1).*cos(psi).*sin( ...
  psi+ (-1).*psi0)+ 2.*dpsi.*dt.^(-1).*h.^(-1).*mu.*sin(psi).*((-1).* ...
  h.*sin(psi)+ h0.*sin(psi0)),4.*dpsi.*dt.^(-1).*h.^(-1).*mu.*r.*cos( ...
  psi)+ (-4).*dpsi.*dt.^(-1).*h.^(-1).*mu.*(r+ (-1).*r0).*cos(psi)+ ( ...
  -4).*dpsi.*dt.^(-1).*h.^(-1).*mu.*r0.*cos(psi)+ (-2).*mu.*r.^(-1).* ...
  vu.*sin(psi)+ (-4).*dpsi.*dt.^(-1).*h.^(-1).*mu.*z.*sin(psi)+ 4.* ...
  dpsi.*dt.^(-1).*h.^(-1).*mu.*(z+ (-1).*z0).*sin(psi)+ 4.*dpsi.*dt.^( ...
  -1).*h.^(-1).*mu.*z0.*sin(psi)+ 2.*dt.^(-1).*mu.*cos(psi).*sin(psi) ...
  + (-2).*dt.^(-1).*mu.*r.^(-1).*r0.*cos(psi).*sin(psi)+ (-2).*dt.^( ...
  -1).*h.^(-1).*mu.*(h.*cos(psi)+ (-1).*h0.*cos(psi0)).*sin(psi)+ (-2) ...
  .*dt.^(-1).*mu.*r.^(-1).*z.*sin(psi).^2+ 2.*dt.^(-1).*mu.*r.^(-1).* ...
  z0.*sin(psi).^2+ (-2).*dt.^(-1).*h.^(-1).*h0.*mu.*sin(psi+ (-1).* ...
  psi0)+ (-2).*dt.^(-1).*h.^(-1).*mu.*cos(psi).*((-1).*h.*sin(psi)+  ...
  h0.*sin(psi0)),(-2).*be.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-2).*z.* ...
  cos(psi).^2+ 2.*be.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-2).*(z+ (-1).* ...
  z0).*cos(psi).^2+ 2.*be.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-2).*z0.* ...
  cos(psi).^2+ 2.*dpsi.*mu.*r.^(-2).*vu.*sin(psi)+ (-2).*be.*dt.^(-1) ...
  .*h.*ka.^(-1).*mu.*r.^(-1).*cos(psi).*sin(psi)+ 2.*be.*dt.^(-1).* ...
  h.*ka.^(-1).*mu.*r.^(-2).*(r+ (-1).*r0).*cos(psi).*sin(psi)+ 2.* ...
  dpsi.*dt.^(-1).*mu.*r.^(-2).*r0.*cos(psi).*sin(psi)+ 2.*be.*dt.^( ...
  -1).*h.*ka.^(-1).*mu.*r.^(-2).*r0.*cos(psi).*sin(psi)+ (-2).*al.* ...
  dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-2).*z.*cos(psi).*sin(psi)+ 2.*al.* ...
  dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-2).*(z+ (-1).*z0).*cos(psi).*sin( ...
  psi)+ 2.*al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-2).*z0.*cos(psi).*sin( ...
  psi)+ (-2).*al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*sin(psi).^2+ 2.* ...
  al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-2).*(r+ (-1).*r0).*sin(psi).^2+  ...
  2.*al.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-2).*r0.*sin(psi).^2+ 2.* ...
  dpsi.*dt.^(-1).*mu.*r.^(-2).*z.*sin(psi).^2+ (-2).*dpsi.*dt.^(-1).* ...
  mu.*r.^(-2).*z0.*sin(psi).^2+ 2.*dt.^(-1).*h0.*mu.*r.^(-2).*sin( ...
  psi).*sin(psi+ (-1).*psi0),(-2).*dpsi.*dt.^(-1).*mu.*r.^(-1).*sin( ...
  psi).^2,0,0,2.*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*z.*cos(psi).* ...
  sin(psi)+ (-2).*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*(z+ (-1).*z0).* ...
  cos(psi).*sin(psi)+ (-2).*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*z0.* ...
  cos(psi).*sin(psi)+ 2.*dt.^(-1).*h.*ka.^(-1).*mu.*sin(psi).^2+ (-2) ...
  .*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*(r+ (-1).*r0).*sin(psi).^2+ ( ...
  -2).*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1).*r0.*sin(psi).^2,2.*dt.^( ...
  -1).*h.*ka.^(-1).*mu.*r.^(-1).*z.*cos(psi).^2+ (-2).*dt.^(-1).*h.* ...
  ka.^(-1).*mu.*r.^(-1).*(z+ (-1).*z0).*cos(psi).^2+ (-2).*dt.^(-1).* ...
  h.*ka.^(-1).*mu.*r.^(-1).*z0.*cos(psi).^2+ 2.*dt.^(-1).*h.*ka.^(-1) ...
  .*mu.*cos(psi).*sin(psi)+ (-2).*dt.^(-1).*h.*ka.^(-1).*mu.*r.^(-1) ...
  .*(r+ (-1).*r0).*cos(psi).*sin(psi)+ (-2).*dt.^(-1).*h.*ka.^(-1).* ...
  mu.*r.^(-1).*r0.*cos(psi).*sin(psi),Ga2.*h+ (-2).*dpsi.*mu.*r.^(-1) ...
  .*sin(psi);(-1).*fn.*h.*r.*cos(psi)+ dpsi.*la.*r.*cos(psi)+ (-2).* ...
  dpsi.*mu.*vu.*cos(psi).^2+ dt.^(-1).*Ga1.*h.*r.*z.*cos(psi).^2+ (-1) ...
  .*dt.^(-1).*Ga1.*h.*r.*z0.*cos(psi).^2+ 2.*h.*la.*cos(psi).*sin( ...
  psi)+ (-1).*h.*ka.*r.^(-2).*cos(psi).*sin(psi)+ 2.*dt.^(-1).*Ga1.* ...
  h.*r.^2.*cos(psi).*sin(psi)+ (-2).*dt.^(-1).*Ga1.*h.*r.*r0.*cos( ...
  psi).*sin(psi)+ 4.*h.*mu.*r.^(-1).*vu.*cos(psi).^2.*sin(psi)+ (-4).* ...
  dpsi.*dt.^(-1).*mu.*z.*cos(psi).^2.*sin(psi)+ 4.*dpsi.*dt.^(-1).* ...
  mu.*z0.*cos(psi).^2.*sin(psi)+ 2.*dpsi.*mu.*vu.*sin(psi).^2+ (-1).* ...
  dt.^(-1).*Ga1.*h.*r.*z.*sin(psi).^2+ dt.^(-1).*Ga1.*h.*r.*z0.*sin( ...
  psi).^2+ (-6).*dpsi.*dt.^(-1).*mu.*r.*cos(psi).*sin(psi).^2+ 6.* ...
  dpsi.*dt.^(-1).*mu.*r0.*cos(psi).*sin(psi).^2+ 6.*dt.^(-1).*h.*mu.* ...
  r.^(-1).*z.*cos(psi).^2.*sin(psi).^2+ (-6).*dt.^(-1).*h.*mu.*r.^( ...
  -1).*z0.*cos(psi).^2.*sin(psi).^2+ (-2).*h.*mu.*r.^(-1).*vu.*sin( ...
  psi).^3+ 2.*dpsi.*dt.^(-1).*mu.*z.*sin(psi).^3+ (-2).*dpsi.*dt.^(-1) ...
  .*mu.*z0.*sin(psi).^3+ 8.*dt.^(-1).*h.*mu.*cos(psi).*sin(psi).^3+ ( ...
  -8).*dt.^(-1).*h.*mu.*r.^(-1).*r0.*cos(psi).*sin(psi).^3+ (-2).* ...
  dt.^(-1).*h.*mu.*r.^(-1).*z.*sin(psi).^4+ 2.*dt.^(-1).*h.*mu.*r.^( ...
  -1).*z0.*sin(psi).^4,(-1).*c0.*ka+ dpsi.*h.^(-1).*ka+ la.*r.*sin( ...
  psi)+ (-2).*mu.*vu.*cos(psi).*sin(psi)+ (-2).*dt.^(-1).*mu.*z.*cos( ...
  psi).*sin(psi).^2+ 2.*dt.^(-1).*mu.*z0.*cos(psi).*sin(psi).^2+ (-2) ...
  .*dt.^(-1).*mu.*r.*sin(psi).^3+ 2.*dt.^(-1).*mu.*r0.*sin(psi).^3,( ...
  -1).*fn.*h.*sin(psi)+ dpsi.*la.*sin(psi)+ dt.^(-1).*Ga1.*h.*z.*cos( ...
  psi).*sin(psi)+ (-1).*dt.^(-1).*Ga1.*h.*z0.*cos(psi).*sin(psi)+ h.* ...
  ka.*r.^(-3).*sin(psi).^2+ 2.*dt.^(-1).*Ga1.*h.*r.*sin(psi).^2+ (-1) ...
  .*dt.^(-1).*Ga1.*h.*r0.*sin(psi).^2+ (-2).*h.*mu.*r.^(-2).*vu.*cos( ...
  psi).*sin(psi).^2+ (-2).*dpsi.*dt.^(-1).*mu.*sin(psi).^3+ (-2).* ...
  dt.^(-1).*h.*mu.*r.^(-2).*z.*cos(psi).*sin(psi).^3+ 2.*dt.^(-1).* ...
  h.*mu.*r.^(-2).*z0.*cos(psi).*sin(psi).^3+ 2.*dt.^(-1).*h.*mu.*r.^( ...
  -2).*r0.*sin(psi).^4,dt.^(-1).*Ga1.*h.*r.*cos(psi).*sin(psi)+ (-2) ...
  .*dpsi.*dt.^(-1).*mu.*cos(psi).*sin(psi).^2+ 2.*dt.^(-1).*h.*mu.* ...
  r.^(-1).*cos(psi).*sin(psi).^3,0,dpsi.*r.*sin(psi)+ h.*sin(psi).^2, ...
  0,0,(-2).*dpsi.*mu.*cos(psi).*sin(psi)+ 2.*h.*mu.*r.^(-1).*cos(psi) ...
  .*sin(psi).^2;h.*la.*cos(psi).^2+ dt.^(-1).*Ga1.*h.*r.^2.*cos(psi) ...
  .^2+ (-1).*dt.^(-1).*Ga1.*h.*r.*r0.*cos(psi).^2+ 2.*h.*mu.*r.^(-1).* ...
  vu.*cos(psi).^3+ (-2).*dpsi.*dt.^(-1).*mu.*z.*cos(psi).^3+ 2.*dpsi.* ...
  dt.^(-1).*mu.*z0.*cos(psi).^3+ fn.*h.*r.*sin(psi)+ (-1).*dpsi.*la.* ...
  r.*sin(psi)+ 4.*dpsi.*mu.*vu.*cos(psi).*sin(psi)+ (-2).*dt.^(-1).* ...
  Ga1.*h.*r.*z.*cos(psi).*sin(psi)+ 2.*dt.^(-1).*Ga1.*h.*r.*z0.*cos( ...
  psi).*sin(psi)+ (-4).*dpsi.*dt.^(-1).*mu.*r.*cos(psi).^2.*sin(psi)+  ...
  4.*dpsi.*dt.^(-1).*mu.*r0.*cos(psi).^2.*sin(psi)+ 4.*dt.^(-1).*h.* ...
  mu.*r.^(-1).*z.*cos(psi).^3.*sin(psi)+ (-4).*dt.^(-1).*h.*mu.*r.^( ...
  -1).*z0.*cos(psi).^3.*sin(psi)+ (-1).*h.*la.*sin(psi).^2+ (-1).* ...
  dt.^(-1).*Ga1.*h.*r.^2.*sin(psi).^2+ dt.^(-1).*Ga1.*h.*r.*r0.*sin( ...
  psi).^2+ (-4).*h.*mu.*r.^(-1).*vu.*cos(psi).*sin(psi).^2+ 4.*dpsi.* ...
  dt.^(-1).*mu.*z.*cos(psi).*sin(psi).^2+ (-4).*dpsi.*dt.^(-1).*mu.* ...
  z0.*cos(psi).*sin(psi).^2+ 6.*dt.^(-1).*h.*mu.*cos(psi).^2.*sin( ...
  psi).^2+ (-6).*dt.^(-1).*h.*mu.*r.^(-1).*r0.*cos(psi).^2.*sin(psi) ...
  .^2+ 2.*dpsi.*dt.^(-1).*mu.*r.*sin(psi).^3+ (-2).*dpsi.*dt.^(-1).* ...
  mu.*r0.*sin(psi).^3+ (-4).*dt.^(-1).*h.*mu.*r.^(-1).*z.*cos(psi).* ...
  sin(psi).^3+ 4.*dt.^(-1).*h.*mu.*r.^(-1).*z0.*cos(psi).*sin(psi) ...
  .^3+ (-2).*dt.^(-1).*h.*mu.*sin(psi).^4+ 2.*dt.^(-1).*h.*mu.*r.^(-1) ...
  .*r0.*sin(psi).^4,la.*r.*cos(psi)+ (-2).*mu.*vu.*cos(psi).^2+ (-2).* ...
  dt.^(-1).*mu.*z.*cos(psi).^2.*sin(psi)+ 2.*dt.^(-1).*mu.*z0.*cos( ...
  psi).^2.*sin(psi)+ (-2).*dt.^(-1).*mu.*r.*cos(psi).*sin(psi).^2+ 2.* ...
  dt.^(-1).*mu.*r0.*cos(psi).*sin(psi).^2,(-1).*fn.*h.*cos(psi)+  ...
  dpsi.*la.*cos(psi)+ dt.^(-1).*Ga1.*h.*z.*cos(psi).^2+ (-1).*dt.^(-1) ...
  .*Ga1.*h.*z0.*cos(psi).^2+ 2.*dt.^(-1).*Ga1.*h.*r.*cos(psi).*sin( ...
  psi)+ (-1).*dt.^(-1).*Ga1.*h.*r0.*cos(psi).*sin(psi)+ (-2).*h.*mu.* ...
  r.^(-2).*vu.*cos(psi).^2.*sin(psi)+ (-2).*dpsi.*dt.^(-1).*mu.*cos( ...
  psi).*sin(psi).^2+ (-2).*dt.^(-1).*h.*mu.*r.^(-2).*z.*cos(psi).^2.* ...
  sin(psi).^2+ 2.*dt.^(-1).*h.*mu.*r.^(-2).*z0.*cos(psi).^2.*sin(psi) ...
  .^2+ 2.*dt.^(-1).*h.*mu.*r.^(-2).*r0.*cos(psi).*sin(psi).^3,dt.^( ...
  -1).*Ga1.*h.*r.*cos(psi).^2+ (-2).*dpsi.*dt.^(-1).*mu.*cos(psi) ...
  .^2.*sin(psi)+ 2.*dt.^(-1).*h.*mu.*r.^(-1).*cos(psi).^2.*sin(psi) ...
  .^2,0,dpsi.*r.*cos(psi)+ h.*cos(psi).*sin(psi),0,0,(-2).*dpsi.*mu.* ...
  cos(psi).^2+ 2.*h.*mu.*r.^(-1).*cos(psi).^2.*sin(psi);(-1).*dpsi.* ...
  dt.^(-1).*r.*cos(psi)+ dpsi.*dt.^(-1).*r0.*cos(psi)+ (-1).*dt.^(-1) ...
  .*h.*r.^(-1).*z.*cos(psi).^2+ dt.^(-1).*h.*r.^(-1).*z0.*cos(psi) ...
  .^2+ h.*r.^(-1).*vu.*sin(psi)+ dpsi.*dt.^(-1).*z.*sin(psi)+ (-1).* ...
  dpsi.*dt.^(-1).*z0.*sin(psi)+ (-2).*dt.^(-1).*h.*cos(psi).*sin(psi) ...
  + 2.*dt.^(-1).*h.*r.^(-1).*r0.*cos(psi).*sin(psi)+ dt.^(-1).*h.*r.^( ...
  -1).*z.*sin(psi).^2+ (-1).*dt.^(-1).*h.*r.^(-1).*z0.*sin(psi).^2,( ...
  -1).*dt.^(-1).*z.*cos(psi)+ dt.^(-1).*z0.*cos(psi)+ (-1).*dt.^(-1).* ...
  r.*sin(psi)+ dt.^(-1).*r0.*sin(psi),h.*r.^(-2).*vu.*cos(psi)+ (-1).* ...
  dpsi.*dt.^(-1).*sin(psi)+ dt.^(-1).*h.*r.^(-2).*z.*cos(psi).*sin( ...
  psi)+ (-1).*dt.^(-1).*h.*r.^(-2).*z0.*cos(psi).*sin(psi)+ (-1).* ...
  dt.^(-1).*h.*r.^(-2).*r0.*sin(psi).^2,(-1).*dpsi.*dt.^(-1).*cos( ...
  psi)+ (-1).*dt.^(-1).*h.*r.^(-1).*cos(psi).*sin(psi),0,0,0,0,(-1).* ...
  h.*r.^(-1).*cos(psi)];

dfdp=[0;(-1).*dpsi.*r.^(-1).*cos(psi)+ 2.*be.*h.*ka.^(-1).*r.^(-1).*cos( ...
  psi)+ 2.*al.*h.*ka.^(-1).*r.^(-1).*sin(psi)+ 2.*h.*r.^(-2).*cos(psi) ...
  .*sin(psi);cos(psi);(-1).*sin(psi);r;(-1).*fu+ Ga2.*vu+ (-2).* ...
  dpsi.^2.*dt.^(-1).*h.^(-2).*mu.*r.*cos(psi)+ 2.*dpsi.^2.*dt.^(-1).* ...
  h.^(-2).*mu.*(r+ (-1).*r0).*cos(psi)+ 2.*dpsi.^2.*dt.^(-1).*h.^(-2) ...
  .*mu.*r0.*cos(psi)+ 2.*be.*dt.^(-1).*ka.^(-1).*mu.*r.^(-1).*z.*cos( ...
  psi).^2+ (-2).*be.*dt.^(-1).*ka.^(-1).*mu.*r.^(-1).*(z+ (-1).*z0).* ...
  cos(psi).^2+ (-2).*be.*dt.^(-1).*ka.^(-1).*mu.*r.^(-1).*z0.*cos( ...
  psi).^2+ 2.*dpsi.^2.*dt.^(-1).*h.^(-2).*mu.*z.*sin(psi)+ (-2).* ...
  dpsi.^2.*dt.^(-1).*h.^(-2).*mu.*(z+ (-1).*z0).*sin(psi)+ (-2).* ...
  dpsi.^2.*dt.^(-1).*h.^(-2).*mu.*z0.*sin(psi)+ 2.*be.*dt.^(-1).* ...
  ka.^(-1).*mu.*cos(psi).*sin(psi)+ (-2).*be.*dt.^(-1).*ka.^(-1).* ...
  mu.*r.^(-1).*(r+ (-1).*r0).*cos(psi).*sin(psi)+ (-2).*be.*dt.^(-1).* ...
  ka.^(-1).*mu.*r.^(-1).*r0.*cos(psi).*sin(psi)+ 2.*al.*dt.^(-1).* ...
  ka.^(-1).*mu.*r.^(-1).*z.*cos(psi).*sin(psi)+ (-2).*al.*dt.^(-1).* ...
  ka.^(-1).*mu.*r.^(-1).*(z+ (-1).*z0).*cos(psi).*sin(psi)+ (-2).*al.* ...
  dt.^(-1).*ka.^(-1).*mu.*r.^(-1).*z0.*cos(psi).*sin(psi)+ 2.*dpsi.* ...
  dt.^(-1).*h.^(-2).*mu.*(h.*cos(psi)+ (-1).*h0.*cos(psi0)).*sin(psi) ...
  + 2.*al.*dt.^(-1).*ka.^(-1).*mu.*sin(psi).^2+ (-2).*al.*dt.^(-1).* ...
  ka.^(-1).*mu.*r.^(-1).*(r+ (-1).*r0).*sin(psi).^2+ (-2).*al.*dt.^( ...
  -1).*ka.^(-1).*mu.*r.^(-1).*r0.*sin(psi).^2+ 2.*dpsi.*dt.^(-1).* ...
  h.^(-2).*h0.*mu.*sin(psi+ (-1).*psi0)+ 2.*dpsi.*dt.^(-1).*h.^(-2).* ...
  mu.*cos(psi).*((-1).*h.*sin(psi)+ h0.*sin(psi0));(1/2).*c0.^2.*ka+ ( ...
  -1/2).*dpsi.^2.*h.^(-2).*ka+ (-1).*fn.*r.*sin(psi)+ dt.^(-1).*Ga1.* ...
  r.*z.*cos(psi).*sin(psi)+ (-1).*dt.^(-1).*Ga1.*r.*z0.*cos(psi).* ...
  sin(psi)+ la.*sin(psi).^2+ (-1/2).*ka.*r.^(-2).*sin(psi).^2+ dt.^(-1) ...
  .*Ga1.*r.^2.*sin(psi).^2+ (-1).*dt.^(-1).*Ga1.*r.*r0.*sin(psi).^2+  ...
  2.*mu.*r.^(-1).*vu.*cos(psi).*sin(psi).^2+ 2.*dt.^(-1).*mu.*r.^(-1) ...
  .*z.*cos(psi).*sin(psi).^3+ (-2).*dt.^(-1).*mu.*r.^(-1).*z0.*cos( ...
  psi).*sin(psi).^3+ 2.*dt.^(-1).*mu.*sin(psi).^4+ (-2).*dt.^(-1).* ...
  mu.*r.^(-1).*r0.*sin(psi).^4;(-1).*fn.*r.*cos(psi)+ dt.^(-1).*Ga1.* ...
  r.*z.*cos(psi).^2+ (-1).*dt.^(-1).*Ga1.*r.*z0.*cos(psi).^2+ la.*cos( ...
  psi).*sin(psi)+ dt.^(-1).*Ga1.*r.^2.*cos(psi).*sin(psi)+ (-1).*dt.^( ...
  -1).*Ga1.*r.*r0.*cos(psi).*sin(psi)+ 2.*mu.*r.^(-1).*vu.*cos(psi) ...
  .^2.*sin(psi)+ 2.*dt.^(-1).*mu.*r.^(-1).*z.*cos(psi).^2.*sin(psi) ...
  .^2+ (-2).*dt.^(-1).*mu.*r.^(-1).*z0.*cos(psi).^2.*sin(psi).^2+ 2.* ...
  dt.^(-1).*mu.*cos(psi).*sin(psi).^3+ (-2).*dt.^(-1).*mu.*r.^(-1).* ...
  r0.*cos(psi).*sin(psi).^3;(-1).*r.^(-1).*vu.*cos(psi)+ (-1).*dt.^( ...
  -1).*r.^(-1).*z.*cos(psi).*sin(psi)+ dt.^(-1).*r.^(-1).*z0.*cos( ...
  psi).*sin(psi)+ (-1).*dt.^(-1).*sin(psi).^2+ dt.^(-1).*r.^(-1).*r0.* ...
  sin(psi).^2];
